_target_: src.models.deepbin_model.DeepBinModel
lr: 0.0001
weight_decay: 0.0005
w_cat: 0.000156
w_gauss: 0.000156
w_rec: 1
input_size: 104
rec_type: "mse"
gaussian_size: 32
num_classes: null
plot_graph_size: 1000
zarr_dataset_path: ""
log_path: "/datahome/datasets/ericteam/csmxrao/DeepMetaBin/mingxing/Metagenomic-Binning/logs"
k: 3
result_path: ""
contignames_path: "sample_data/contignames.npz"
contig_path: "sample_data/contigs.fasta"
