_target_: src.models.gmgat_model.GMGATModel

in_channels: 
  - 32
  - 64
  - 128
out_channels: 
  - 64
  - 128
  - 128
num_heads: 16
latent_dim: 128
dropout: 0.1
num_blocks: 2
use_bias: True
lr: 0.0001
weight_decay: 0.0005
