_target_: src.models.gmgat_model.GMGATModel

encoder_in_channels: 
  - 32
  - 64
encoder_out_channels: 
  - 64
  - 128
decoder_in_channels:
  - 1
  - 16
decoder_out_channels:
  - 16
  - 32
num_heads: 16
latent_dim: 128
dropout: 0.1
num_blocks: 2
use_bias: True
lr: 0.0001
weight_decay: 0.0005
