_target_: src.models.vae_model.VAEModel

encoder_input_dim: 104
encoder_hidden_dim: 128
encoder_latent_dim: 128
decoder_latent_dim: 128
decoder_hidden_dim: 128
decoder_output_dim: 104
w_rec: 1
w_kl: 0.01
lr: 0.0001
