_target_: src.datamodules.deepmetabin_datamodule.DeepMetaBinDataModule

zarr_dataset_path: "/datahome/datasets/ericteam/csmxrao/DeepMetaBin/mingxing/Metagenomic-Binning/data/cami-m1.zarr"
use_neighbor_feature: True
k: 5
sigma: 1
batch_size: 400
train_val_test_split: [1, 0, 0]
num_workers: 0
pin_memory: False
